### ISSUE TITLE
Add PostgreSQL as the database

### ISSUE THREAD

**Issue by Barissa-Imran** [savannah-Silica/django-backend#10]
Configure database settings and connect the project to a database.
- Use generic Names and Keys which will be changed later
- Don't forget to use environment variables which you'll share the .env file
- Make sure to include in the README how one might go about setting up POSTGRES on their machine so that when they execute `python manage.py migrate` it won't throw an error.

Refer: [here](https://stackpython.medium.com/how-to-start-django-project-with-a-database-postgresql-aaa1d74659d8)

> Don't forget the pgAdmin is important to the docs

@savannah-Silica/django-devs check this issue out. Needs extra attention

**Comment by IanoNjuguna** [comment]
I'm willing to tackle this issue.

**Comment by Collins-Omariba** [comment]
It will be great if the issue is closed before the end of today . Other issues depend on closing this one.

**Comment by IanoNjuguna** [comment]
Noted. I'm working hard on it.

**Comment by Collins-Omariba** [comment]
Requested changes 
 - Use the already used 'dotenv module' not 'environ' for the environment variables (Check Readme env setup  section )
 - The django-postgres/env/bin/Activate.ps1 file shouldn't be part of the pull request.

**Comment by Fredrick-Waihenya** [comment]
Is this issue closed yet

**Comment by Barissa-Imran** [comment]
> Is this issue closed yet

Not yet, there's a problem with the pull request which still hasn't been attended to.

**Comment by Collins-Omariba** [comment]
@IanoNjuguna some files shouldn't be pushed to GitHub e.g. the env file  (use gitignore) , the pull request contains over 5000 + changed files ,check it .you can reset your commit or open a new pull request after making changes

**Comment by IanoNjuguna** [comment]
Sure thing Collins

**Comment by Collins-Omariba** [comment]
How is the progress on this issue
