### ISSUE TITLE
Create models for Projects Microservice

### ISSUE THREAD

**Issue by Barissa-Imran** [savannah-Silica/django-backend#13]
Add the specific models for the projects service as specified by the ERD.

> Make the necessary imports
> Make production ready models

See [reference](https://cloud.smartdraw.com/editor.aspx?depoId=38611778&credID=-41609378&pubDocShare=EF70B98534AF252A4CD0F522FF4ABFCCEEE)

@savannah-Silica/django-devs

**Comment by BrianOyollo** [comment]
Let me work on this
