### ISSUE TITLE
Add Serializers for Project Microservice

### ISSUE THREAD

**Issue by Barissa-Imran** [savannah-Silica/django-backend#14]
Add serializers for the project service models. Please note that this issue is dependent on issue #13 being complete

> Make the necessary imports

See [reference](https://www.django-rest-framework.org/tutorial/quickstart/#serializers)

**Comment by kema-ray** [comment]
I can work on this once issue #13 is complete

**Comment by Fredrick-Waihenya** [comment]
I can help with this issue

**Comment by Collins-Omariba** [comment]
issue #13 has been closed and a corresponding pull request merged, you are free to work on this issue.

**Comment by Fredrick-Waihenya** [comment]
Apologies,I hadn't seen the issue was assigned to me will deal with it by the end of the day.
