### ISSUE TITLE
Add a CONTRIBUTIONS.MD

### ISSUE THREAD

**Issue by Collins-Omariba** [savannah-Silica/django-backend#16]
Add a contributions.md file , you can use information from the Readme .

**Comment by symonkipkemei** [comment]
Hi Collins, I would like to take up this issue.

**Comment by Collins-Omariba** [comment]
Good. Try and finish it fast since it will guide new contributers.

**Comment by Collins-Omariba** [comment]
It will be great if the issue is closed before the end of today . Other issues depend on closing this one.

**Comment by symonkipkemei** [comment]
branch description updated
