### ISSUE TITLE
projects: Correct naming of the serializers file

### ISSUE THREAD

**Issue by Barissa-Imran** [savannah-Silica/django-backend#32]
The file should be named `serializers.py`

@savannah-Silica/django-devs please take a look

**Comment by nal-liam** [comment]
hey @Barissa-Imran  can i work on this issue

**Comment by Barissa-Imran** [comment]
@nal-liam create a pull request for this if complete so that you can work on other issues

**Comment by nal-liam** [comment]
But have already created a pull request and says merge blocked needs a
review

**Comment by Collins-Omariba** [comment]
some files shouldn't be pushed to GitHub e.g. the env file  (use gitignore) , the pull request contains over 5000 + changed files ,check it .you can reset your commit or open a new pull request after making changes
