### ISSUE TITLE
projects: create project detail view

### ISSUE THREAD

**Issue by Barissa-Imran** [savannah-Silica/django-backend#34]
- Add the project detail view
- use best practices while creating an API
- Comment your code
- Error handling should also be prioritized

**Comment by Kibet-mutai** [comment]
assign

**Comment by Kibet-mutai** [comment]
Hello, should I include urls?

**Comment by Barissa-Imran** [comment]
> Hello, should I include urls?

Yes, add the urls that are connected to the view

**Comment by Collins-Omariba** [comment]
Appreciated
