### ISSUE TITLE
remove unused modules from the requirements file

### ISSUE THREAD

**Issue by JimmyTron** [savannah-Silica/django-backend#51]
most of the modules in this list are not used by the Django project and this would mean the modules will be sitting on your Dev server just occupying space. 

To mitigate this set up a virtual environment and only install modules that your project needs then populate the `requirements.txt` 

![image](https://user-images.githubusercontent.com/23496280/204929448-0c40ed9f-b6e7-4a09-b01f-36fddde43380.png)

**Comment by Barissa-Imran** [comment]
@JimmyTron Thank you for noticing. would you be up for taking this on?

**Comment by JimmyTron** [comment]
ok let me have a go at it

**Comment by JimmyTron** [comment]
@Barissa-Imran any help with documentation so that i could know whate modules to have installed.

**Comment by JimmyTron** [comment]
![image](https://user-images.githubusercontent.com/23496280/205377029-d21aa71e-194d-49c4-9ee3-52581a72e299.png)
comparing this file with  
![](https://user-images.githubusercontent.com/23496280/204929448-0c40ed9f-b6e7-4a09-b01f-36fddde43380.png)
this one makes it evident

**Comment by Barissa-Imran** [comment]
some dependencies are written there as a result of the operating system that was used and some come as a result of others
