### ISSUE TITLE
Load Secret Key as ENV variable

### ISSUE THREAD

**Issue by Barissa-Imran** [savannah-Silica/django-backend#7]
The secret key in settings is currently public. Change this so that it only exists in a `.env` file locally. Update the readme with steps on how one might create their own secret key for the project to use locally. Don't forget to update the `requirements.txt`

- use the python library `dotenv` 
- use the variable `SECRET_KEY`

@savannah-Silica/django-devs

**Comment by WalobwaD** [comment]
And the DEBUG feature? Or you just need the SECRET_KEY to be in the .env file?

**Comment by Barissa-Imran** [comment]
> And the DEBUG feature? Or you just need the SECRET_KEY to be in the .env file?

Yes, you can also do that part.

**Comment by WalobwaD** [comment]
Yes, if you can
